USE ProUTN;
GO

/* Store Procedures Headquarters */
CREATE PROCEDURE SP_GETNEXTCODEHEADQUARTERS
AS
BEGIN
	SELECT MAX(HEADQUARTERS_ID) FROM HEADQUARTERS;
END;
GO

CREATE PROCEDURE SP_EXISTPHEADQUARTERS
@ID NUMERIC
AS
BEGIN
	SELECT COUNT(HEADQUARTERS_ID) FROM HEADQUARTERS WHERE HEADQUARTERS_ID =@ID;
END;
GO

CREATE PROCEDURE SP_INSERTHEADQUARTERS
@ID NUMERIC,
@NAME VARCHAR(50),
@STATE NUMERIC(1)  
AS
BEGIN
	INSERT INTO HEADQUARTERS (HEADQUARTERS_ID,NAME,STATE,DELETED) 
	VALUES (@ID,@NAME,@STATE,1);
END;
GO

CREATE PROCEDURE SP_MODIFYHEADQUARTERS
@ID NUMERIC,
@NAME VARCHAR(50),
@STATE NUMERIC(1)
AS 
BEGIN
	UPDATE HEADQUARTERS
	SET NAME = @NAME,
	STATE = @STATE
	WHERE HEADQUARTERS_ID = @ID; 
END;
GO

CREATE PROCEDURE SP_DELETEHEADQUATERS
@ID NUMERIC
AS
BEGIN
	UPDATE HEADQUARTERS
	SET DELETED = 0
	WHERE HEADQUARTERS_ID = @ID;
END;
GO

CREATE PROCEDURE SP_GETALLHEADQUARTERS
AS
BEGIN
	SELECT HEADQUARTERS_ID,NAME,STATE 
	FROM HEADQUARTERS
	WHERE DELETED = 1;
END;
GO

CREATE PROCEDURE SP_GETPHEADQUARTERS
@ID NUMERIC
AS
BEGIN
	SELECT HEADQUARTERS_ID,NAME,STATE 
	FROM HEADQUARTERS
	WHERE HEADQUARTERS_ID = @ID AND
	DELETED = 1;
END;
GO

CREATE PROCEDURE SP_GETALLHEADQUARTERSACTIVE
AS
BEGIN
	SELECT HEADQUARTERS_ID,NAME,STATE 
	FROM HEADQUARTERS 
	WHERE STATE = 1 AND
	DELETED = 1;
END;
GO
