USE ProUTN;
GO
/* ---- Store Procedures INTERNAL_DESIGNATION ---- */
--to get last code
CREATE PROCEDURE SP_GETNEXTCODEINTERNAL_DESIGNATION
AS
BEGIN
	SELECT MAX(DESIGNATION_ID)
	FROM INTERNAL_DESIGNATION;
END;
GO

--to check that a internal_designation exists
CREATE PROCEDURE SP_EXISTINTERNAL_DESIGNATION
@ID NUMERIC
AS
BEGIN
	SELECT COUNT(DESIGNATION_ID)
	FROM INTERNAL_DESIGNATION
	WHERE DESIGNATION_ID = @ID;
END;
GO

--to insert a internal_designation
CREATE PROCEDURE SP_INSERTINTERNAL_DESIGNATION
@ID NUMERIC,
@DESCRIPTION VARCHAR(100),
@SALARY MONEY,
@ANNUITY FLOAT,
@STATE NUMERIC(1)  
AS
BEGIN
	INSERT INTO INTERNAL_DESIGNATION (DESIGNATION_ID, DESCRIPTION, BASE_SALARY,ANNUITY, STATE, DELETED)
	VALUES ( @ID, @DESCRIPTION, @SALARY, @ANNUITY, @STATE, 1 );
END;
GO

--to modify internal_designation
CREATE PROCEDURE SP_MODIFYINTERNAL_DESIGNATION
@ID NUMERIC,
@DESCRIPTION VARCHAR(100),
@SALARY MONEY,
@ANNUITY FLOAT,
@STATE NUMERIC(1)  
AS
BEGIN
	UPDATE INTERNAL_DESIGNATION
	SET DESCRIPTION = @DESCRIPTION,
	BASE_SALARY = @SALARY,
	ANNUITY = @ANNUITY,
	STATE = @STATE
	WHERE DESIGNATION_ID = @ID;
END;
GO 

-- to delete internal designation
CREATE PROCEDURE SP_DELETEINTERNALDESIGNATION
@ID NUMERIC
AS
BEGIN
	UPDATE INTERNAL_DESIGNATION
	SET DELETED = 0
	WHERE DESIGNATION_ID = @ID;
END;
GO

--to get all internal_designation
CREATE PROCEDURE SP_GETALLINTERNAL_DESIGNATION
AS
BEGIN
	SELECT DESIGNATION_ID, DESCRIPTION, BASE_SALARY, ANNUITY, STATE
	FROM INTERNAL_DESIGNATION
	WHERE DELETED = 1;
END;
GO

--to get internal_designation by code
CREATE PROCEDURE SP_GETINTERNAL_DESIGNATION
@ID NUMERIC
AS
BEGIN
	SELECT DESIGNATION_ID, DESCRIPTION, BASE_SALARY, ANNUITY, STATE
	FROM INTERNAL_DESIGNATION
	WHERE DESIGNATION_ID = @ID AND
	DELETED = 1;
END;
GO

--to get all internal_designation active
CREATE PROCEDURE SP_GETALLINTERNAL_DESIGNATIONACTIVE
AS
BEGIN
	SELECT DESIGNATION_ID, DESCRIPTION, BASE_SALARY, ANNUITY, STATE
	FROM INTERNAL_DESIGNATION
	WHERE STATE = 1 AND
	DELETED = 1;
END;
GO

--to get all internal_designation desactive
CREATE PROCEDURE SP_GETALLINTERNAL_DESIGNATIONDESACTIVE
AS
BEGIN
	SELECT DESIGNATION_ID, DESCRIPTION, BASE_SALARY, ANNUITY, STATE
	FROM INTERNAL_DESIGNATION
	WHERE STATE = 0 AND
	DELETED = 1;
END;
GO

/* ---- End INTERNAL_DESIGNATION Procedures ---- */