USE ProUTN;
GO
/* ---- Store Procedures Program ---- */
--to get last code
CREATE PROCEDURE SP_GETNEXTCODEPROGRAM
AS
BEGIN
	SELECT MAX(PROGRAM_ID) 
	FROM PROGRAM;
END;
GO

--to check that a program exists
CREATE PROCEDURE SP_EXISTPROGRAM
@ID NUMERIC
AS
BEGIN
	SELECT COUNT(PROGRAM_ID) 
	FROM PROGRAM 
	WHERE PROGRAM_ID =@ID;
END;
GO

--to insert a program
CREATE PROCEDURE SP_INSERTPROGRAM
@ID NUMERIC,
@NAME VARCHAR(50),
@STATE NUMERIC(1),
@UNIT BIGINT
AS
BEGIN
	INSERT INTO PROGRAM (PROGRAM_ID,NAME,STATE,UNIT, DELETED) 
	VALUES (@ID,@NAME,@STATE,@UNIT, 1);
END;
GO

--to modify program
CREATE PROCEDURE SP_MODIFYPROGRAM
@ID NUMERIC,
@NAME VARCHAR(50),
@STATE NUMERIC(1),
@UNIT BIGINT
AS 
BEGIN
	UPDATE PROGRAM
	SET NAME = @NAME,
	STATE = @STATE,
	UNIT = @UNIT
	WHERE PROGRAM_ID = @ID; 
END;
GO

-- to delete program
CREATE PROCEDURE SP_DELETEPROGRAM
@ID NUMERIC
AS
BEGIN
	UPDATE PROGRAM
	SET DELETED = 0
	WHERE PROGRAM_ID = @ID;
END;
GO

--to get all program
CREATE PROCEDURE SP_GETALLPROGRAM
AS
BEGIN
	SELECT P.PROGRAM_ID,P.NAME,P.STATE,P.UNIT
	FROM PROGRAM P
	WHERE DELETED = 1;
END;
GO

--to get program by code
CREATE PROCEDURE SP_GETPROGRAM
@ID NUMERIC
AS
BEGIN
	SELECT P.PROGRAM_ID,P.NAME,P.STATE,P.UNIT
	FROM PROGRAM P
	WHERE P.PROGRAM_ID = @ID AND
	DELETED = 1;
END;
GO

--to get all program active
CREATE PROCEDURE SP_GETALLPROGRAMACTIVED
AS
BEGIN
	SELECT P.PROGRAM_ID,P.NAME,P.STATE,P.UNIT
	FROM PROGRAM P
	WHERE P.STATE = 1 AND
	DELETED = 1;
END;
GO

--to get all program desactive
CREATE PROCEDURE SP_GETALLPROGRAMDESACTIVED
AS
BEGIN
	SELECT P.PROGRAM_ID,P.NAME,P.STATE,P.UNIT
	FROM PROGRAM P
	WHERE P.STATE = 0 AND
	DELETED = 1;
END;
GO



/* ---- End Program Procedures ---- */