use ProUTN
go

/* ---- Store Procedures RoleModule ---- */
CREATE PROCEDURE SP_EXISTROLEMODULE
@ID NUMERIC
AS
BEGIN
	SELECT COUNT(ROLE_ID) 
	FROM ROLEMODULE 
	WHERE ROLE_ID =@ID;
END;
GO

CREATE PROCEDURE SP_DELETEROLEMODULE
@ID NUMERIC
AS
BEGIN
	DELETE FROM ROLEMODULE 
	WHERE ROLE_ID =@ID;
END;
GO

CREATE PROCEDURE SP_INSERTROLEMODULE
@ID_ROLE NUMERIC,
@ID_MODULE NUMERIC
AS
BEGIN

INSERT INTO ROLEMODULE (ROLE_ID,SYSTEMMODULES_ID)
     VALUES (@ID_ROLE,@ID_MODULE);

END;
go


CREATE PROCEDURE SP_GETALLROLEMODULEBYROLE
@ID NUMERIC
AS
BEGIN
	SELECT RM.ROLE_ID,RM.SYSTEMMODULES_ID,S.DESCRIPTION
	FROM ROLEMODULE RM,SYSTEMMODULE S
	WHERE RM.SYSTEMMODULES_ID=S.SYSTEMMODULES_ID
	AND RM.ROLE_ID=@ID;
END;
GO

select * from ROLE