USE ProUTN;
GO

CREATE PROCEDURE SP_GETALLDAY
AS
BEGIN

	SELECT DAY_ID,DESCRIPTION
	FROM DAY;

END;
GO

INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (1	, 'Lunes');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (2	, 'Martes');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (3	, 'Miercoles');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (4	, 'Jueves');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (5	, 'Viernes');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (6	, 'Sábado');
INSERT INTO DAY (DAY_ID, DESCRIPTION) VALUES (7	, 'Domingo');