USE ProUTN;
GO

--to insert a internal_designation
CREATE PROCEDURE SP_INSERTEXTERNALDESIGNATION_JOURNEY
@IDEXTERNAL NUMERIC,
@IDJOURNEY NUMERIC
AS
BEGIN

INSERT INTO [dbo].[EXT_DESIG_JOURNEY]
           ([EXTERNAL_DESIGNATION_ID],[JOURNEY_ID])
     VALUES (@IDEXTERNAL,@IDJOURNEY)
END;
GO
