USE ProUTN;
GO
/* ---- Store Procedures Journey ---- */
--to get last code
--drop procedure SP_GETNEXTCODEJOURNEY go
CREATE PROCEDURE SP_GETNEXTCODEJOURNEY
AS
BEGIN
	SELECT MAX(JOURNEY_ID)
	FROM JOURNEY;
END;
GO
--drop procedure SP_EXISTJOURMEY go
CREATE PROCEDURE SP_EXISTJOURMEY
@ID NUMERIC
AS
BEGIN
	SELECT COUNT(JOURNEY_ID)
	FROM JOURNEY
	WHERE JOURNEY_ID = @ID;
END;
GO

--to insert a JOURNEY
CREATE PROCEDURE SP_INSERTJOURNEY
@ID NUMERIC,
@DAY_ID NUMERIC,
@START time,
@FINISH time
AS
BEGIN
	INSERT INTO [dbo].[JOURNEY] ([JOURNEY_ID],[DAY_ID],[START],[FINISH])
	VALUES(@ID,@DAY_ID,@START,@FINISH)
END;
GO
