USE ProUTN;
GO
/* ---- Store Procedures TEACHER_SCHEDULE ---- */
--to get last code
CREATE PROCEDURE SP_GETNEXTCODETEACHER_SCHEDULE
AS
BEGIN
	SELECT MAX(TEACHER_SCHEDULE_ID) 
	FROM TEACHER_SCHEDULE;
END;
GO

--to insert a CLASSROOM_SCHEDULE
--drop procedure SP_INSERT_TEACHER_SCHEDULE
CREATE PROCEDURE SP_INSERT_TEACHER_SCHEDULE
@TEACHER_SCHEDULE_ID NUMERIC,
@TEACHER_ID NUMERIC,
@PERIOD_ID NUMERIC,
@DIA_ID NUMERIC,
@Course_ID NUMERIC,
@INITIAL_HOUR TIME,
@FINAL_HOUR TIME,
@ACADEMICOFFER_ID NUMERIC
AS
BEGIN

INSERT INTO [dbo].[TEACHER_SCHEDULE]
           ([TEACHER_SCHEDULE_ID],[TEACHER_ID],[PERIOD_ID],[DAY_ID]
           ,[Course_ID],[INITIAL_HOUR],[FINAL_HOUR],[STATE],[ACADEMIC_OFFER_ID])
     VALUES
           (@TEACHER_SCHEDULE_ID,@TEACHER_ID,@PERIOD_ID,@DIA_ID,@Course_ID,@INITIAL_HOUR,@FINAL_HOUR,1,@ACADEMICOFFER_ID)

END;
GO


--drop procedure SP_TEACHER_BY_SCHEDULE
create procedure SP_TEACHER_BY_SCHEDULE
@period numeric,
@inicialHour time,
@finalhour time,
@day1 numeric,
@day2 numeric,
@day3 numeric,
@day4 numeric,
@day5 numeric,
@day6 numeric,
@day7 numeric
as
begin 
	DECLARE @STARTDATE date = (SELECT p.STARTDATE FROM PERIOD P WHERE P.PERIOD_ID=@period);
	DECLARE @ENDDATE date = (SELECT p.FINALDATE FROM PERIOD P WHERE P.PERIOD_ID=@period);
   SELECT T.[TEACHER_ID],T.[NAME],T.[SURNAME],T.[PHONE],T.[CELEPHONE],T.[MAIL],T.[POSITION_ID],ID.DESCRIPTION
   FROM TEACHER T,INTERNAL_DESIGNATION ID
   WHERE T.POSITION_ID=ID.DESIGNATION_ID and T.STATE=1 AND T.DELETED=1
   AND T.TEACHER_ID not in
   (SELECT T.TEACHER_ID FROM TEACHER T, TEACHER_SCHEDULE TS,PERIOD PE
   WHERE T.TEACHER_ID=TS.TEACHER_ID AND  TS.PERIOD_ID=PE.PERIOD_ID And
   (TS.DAY_ID=@day1 or TS.DAY_ID=@day2 or TS.DAY_ID=@day3 or TS.DAY_ID=@day4 or TS.DAY_ID=@day5 or TS.DAY_ID=@day6 or TS.DAY_ID=@day7)
   	AND (((@inicialHour between TS.INITIAL_HOUR and  TS.FINAL_HOUR) or ( @finalhour between TS.INITIAL_HOUR and  TS.FINAL_HOUR)) 
	or ((TS.INITIAL_HOUR between @inicialHour and @finalhour) or (TS.FINAL_HOUR between @inicialHour and @finalhour))) 
   AND (((@STARTDATE between PE.STARTDATE and  PE.FINALDATE) or ( @ENDDATE between PE.STARTDATE and  PE.FINALDATE)) 
	or ((PE.STARTDATE between @STARTDATE and @ENDDATE) or (PE.FINALDATE between @STARTDATE and @ENDDATE))) 
	)AND T.TEACHER_ID not in
	(SELECT T.TEACHER_ID FROM TEACHER T, EXTERNAL_DESIGNATION EX,EXT_DESIG_JOURNEY EXJ,JOURNEY J
		WHERE T.TEACHER_ID=EX.TEACHER_ID  AND EX.DESIGNATION_ID=EXJ.EXTERNAL_DESIGNATION_ID AND EXJ.JOURNEY_ID=J.JOURNEY_ID AND 
		(J.DAY_ID=@day1 or J.DAY_ID=@day2 or J.DAY_ID=@day3 or J.DAY_ID=@day4 or J.DAY_ID=@day5 or J.DAY_ID=@day6 or J.DAY_ID=@day7)
		AND (((@inicialHour between J.START and  J.FINISH) or ( @finalhour between J.START and  J.FINISH)) 
		or ((J.START between @inicialHour and @finalhour) or (J.FINISH between @inicialHour and @finalhour))) 
		AND (((@STARTDATE between EX.INITIAL_DATE and  EX.FINAL_DATE) or ( @ENDDATE between EX.INITIAL_DATE and  EX.FINAL_DATE)) 
		or ((EX.INITIAL_DATE between @STARTDATE and @ENDDATE) or (EX.FINAL_DATE between @STARTDATE and @ENDDATE))) 
	)
end;
GO