USE ProUTN;
GO

--TO GET LAST CODE
CREATE PROCEDURE SP_GETNEXTCODEWAITINGLIST
AS
BEGIN
	SELECT MAX(WAITING_LIST_ID) 
	FROM WAITING_LIST;
END;
GO

--TO GET LAST CODE TENTATIVE_SHCEDULE
CREATE PROCEDURE SP_GET_NEXT_CODE_TENTATIVE_SHCEDULE
AS
BEGIN
	SELECT MAX(TENTATIVE_SHEDULE_ID) 
	FROM TENTATIVE_SCHEDULE;
END;
GO


--TO INSERT A CUSTOMER
--Drop proc SP_INSERT_WAITINGLIST
CREATE PROCEDURE SP_INSERT_WAITINGLIST
	@WAITING_LIST_ID NUMERIC,
	@ID VARCHAR(15),
	@NAME VARCHAR(50),
	@SURNAME VARCHAR(50),
	@PHONE VARCHAR(15),
	@CELLPHONE VARCHAR(15),
	@MAIL VARCHAR(100),
	@PERIOD NUMERIC,
	@COURSE NUMERIC,
	@DAY VARCHAR(15),
	@CONTACTED NUMERIC(1)
AS
BEGIN
	INSERT INTO WAITING_LIST(WAITING_LIST_ID, ID, NAME, SURNAME, PHONE, CELLPHONE, MAIL, PERIOD_ID,COURSE_ID,DAY, CONTACTED)
	VALUES( @WAITING_LIST_ID, @ID, @NAME, @SURNAME, @PHONE, @CELLPHONE, @MAIL, @PERIOD,@COURSE,@DAY, @CONTACTED );
END;
GO

 
--TO MODIFY WAITING_LIST_
CREATE PROCEDURE SP_MODIFY_WAITING_LIST
	@WAITING_LIST_ID NUMERIC,
	@CONTACTED NUMERIC(1)
AS 
BEGIN
	UPDATE WAITING_LIST 
	SET CONTACTED = @CONTACTED 
	WHERE WAITING_LIST_ID = @WAITING_LIST_ID
END;
GO


--TO GET ALL CUSTOMER FROM WAITING LIST UNCONTACTED
--DROP PROC SP_GET_ALL_CUSTOMER_BY_PERIOD
CREATE PROCEDURE SP_GET_ALL_CUSTOMER_BY_PERIOD
@PERIOD NUMERIC
AS
BEGIN
	SELECT WAITING_LIST_ID AS CODE,ID,CONCAT(WAITING_LIST.NAME,' ',SURNAME) AS NAMEC,PHONE,CELLPHONE,MAIL,PERIOD.NAME, COURSE.DESCRIPTION ,DAY,CONTACTED
	FROM WAITING_LIST, PERIOD , COURSE
	WHERE WAITING_LIST.PERIOD_ID = @PERIOD AND PERIOD.PERIOD_ID = WAITING_LIST.PERIOD_ID AND COURSE.COURSE_ID = WAITING_LIST.COURSE_ID
	ORDER BY CONTACTED,ID ASC;
END;
GO


--TO GET ALL CUSTOMER FROM WAITING LIST CONTACTED
--DROP PROC SP_GET_ALL_CUSTOMER_2
CREATE PROCEDURE SP_GET_ALL_CUSTOMER_2
@PERIOD NUMERIC
AS
BEGIN
	SELECT WAITING_LIST_ID AS CODE,ID,CONCAT(WAITING_LIST.NAME,' ',SURNAME) AS NAMEC,PHONE,CELLPHONE,MAIL,PERIOD.NAME, COURSE.DESCRIPTION ,DAY,CONTACTED
	FROM WAITING_LIST, PERIOD , COURSE
	WHERE WAITING_LIST.PERIOD_ID = @PERIOD AND PERIOD.PERIOD_ID = WAITING_LIST.PERIOD_ID AND COURSE.COURSE_ID = WAITING_LIST.COURSE_ID
	ORDER BY WAITING_LIST_ID ,CONTACTED DESC;
END;
GO

	
--TO GET ALL CUSTOMER FROM WAITING LIST BY COURS
--DROP PROC SP_GET_ALL_CUSTOMER_BY_COURSE
CREATE PROCEDURE SP_GET_ALL_CUSTOMER_BY_COURSE
@PERIOD NUMERIC
AS
BEGIN
	SELECT WAITING_LIST_ID AS CODE,ID,CONCAT(WAITING_LIST.NAME,' ',SURNAME) AS NAMEC,PHONE,CELLPHONE,MAIL,PERIOD.NAME, COURSE.DESCRIPTION ,DAY,CONTACTED
	FROM WAITING_LIST, PERIOD , COURSE
	WHERE WAITING_LIST.PERIOD_ID = @PERIOD AND PERIOD.PERIOD_ID = WAITING_LIST.PERIOD_ID AND COURSE.COURSE_ID = WAITING_LIST.COURSE_ID
	ORDER BY COURSE.COURSE_ID,ID ASC;
END;
GO


